### ISSUE TITLE
Measure benchmarks with AOT compiled code

### ISSUE THREAD

**Issue by mit-mit** [unsuitable001/dart_cronet_sample#2]
Most production Dart code is AOT compiled. It would thus be good to collect the benchmarks (https://github.com/unsuitable001/dart_cronet_sample/blob/master/benchmark/benchmark.sh) using AOT compilation. To compile the terminal programs to AOT, use `dart compile exe`; for details see https://dart.dev/tools/dart-compile.

**Comment by unsuitable001** [comment]
Implemented it. Now, the benchmarking looks even more interesting. I expected it though. As AOT compilation may speed up Dart code, I think it will not reduce the overhead of `ffi`,  `dlfcn` and `native port`.

cc @dcharkes @mannprerak2
